### ISSUE TITLE
Font too big

### ISSUE THREAD

**Issue by sebien0077** [BenRoe/MMM-SystemStats#22]
Can we do something to modify size of police eaily?

**Comment by BenRoe** [comment]
Hi,
what do you mean with size of police?

**Comment by Antgr36** [comment]
I would like to ask you if it is possible to change the module size because it looks too big according to the other modules. I tried to do it but I didn’t find any CSS file in its folder to customize it.

**Comment by 0xueping** [comment]
yes, the default font size of this module is more bigger. Who can tell us how to config the font size? Thanks in advance!

**Comment by Antgr36** [comment]
@gaoxueping Try this in your custom CSS:
```
.MMM-SystemStats{
transform: scale(0.90, 0.90);
}
```
This will reduce tha hole size of the module. Not just the font size. Abjust the the values according to your mirror space.

**Comment by 0xueping** [comment]
@Antgr36 

Wow~, I have done it according as your method. it's perfect!
Thank you very very much!

**Comment by BenRoe** [comment]
Sorry have less time. Thanks @Antgr36 for helping.

**Comment by bert269** [comment]
Thanks. This is not working as coded. Nothing happens. Doing a JSLINT against the code, I get the message: unscalled scale. 
When I change the code to be like the rest of the format: transform: "scale(0.60, 0.60)", - nothing happens either.
What am I missing here?

{
            module: "MMM-SystemStats",
            transform: "scale(0.60, 0.60)",
            position: "top_right",
            config: {........

**Comment by skandragon** [comment]
> Thanks. This is not working as coded. Nothing happens. Doing a JSLINT against the code, I get the message: unscalled scale.
> When I change the code to be like the rest of the format: transform: "scale(0.60, 0.60)", - nothing happens either.
> What am I missing here?
> 
> {
> module: "MMM-SystemStats",
> transform: "scale(0.60, 0.60)",
> position: "top_right",
> config: {........

I believe you need to put the CSS into a custom CSS file, such as `css/custom.css` and not the `config.js` file.
