### ISSUE TITLE
No System Stats displaying on screen

### ISSUE THREAD

**Issue by WIleyAU** [BenRoe/MMM-SystemStats#4]
Hi,

I apologize in advance, while I'm not new to programming I am a complete noob with regards to the Raspberry Pi and javascript - I assume my issues are thus related & hoping you can help me out.

I've downloaded & installed the module & updated the config file as per the instructions, but I am not seeing any system stats displayed on my screen when I start the MM. I did see there was a dependency on async being installed.... Does that need to be installed in addition to the SystemStats module, or does the npm install within the SS dir complete that task? If  I have to install it separately, does this need to be completed prior to installing the SS module? And do I need to install async within the SS module or a parent module? 

Thanking you in advance for both you patience & assistance!

**Comment by BenRoe** [comment]
Hi,
to install the dependency's go into the module folder `cd MMM-SystemStats` and install async with  `npm install`

**Comment by WIleyAU** [comment]
Hi,

That's what I did & I couldn't get it to work. I've just finished completely rebuilding my MM (fresh OS & MM install) and it all works now - so must have been a noob issue.

I appreciate the swift response, many thanks!

**Comment by dewmguy** [comment]
@BenRoe might want to include the async dependency installation instructions on the homepage for the rest of us. I followed the instructions on the homepage, including the part that says:

`cd MMM-SystemStats/ && npm install`

I assume this is the line that is supposed to install async?

~The module still doesn't show up for me.~

**The module lines output "`[icon] loading &hellip;`"**

**Comment by BenRoe** [comment]
The other modules are shown? Maybe a similar problem like WIleyAU

You are right.

- `cd MMM-SystemStats/` says go to the MMM-SystemStats directory.
- `&&` combines two commands
- `npm install` installs all node.js dependencies from the [package.json](https://github.com/BenRoe/MMM-SystemStats/blob/master/package.json) file

**Comment by v4r23** [comment]
I also get

> The module lines output "[icon] loading &hellip;"

Any ideas?

**Comment by cyberdie** [comment]
Same here.
Any help?

**Comment by BenRoe** [comment]
Hello,
sorry i don't have the time to maintain this repository.
If you are interested, i can invite you.

**Comment by cyberdie** [comment]
ok, thanks anyway.
I solved reinstalling
